lat9/ZCA-Bootstrap-Template

includes/templates/bootstrap/modalboxes/tpl_attributes_qty_prices.php
includes/templates/bootstrap/modalboxes/tpl_image.php
includes/templates/bootstrap/modalboxes/tpl_image_additional.php
includes/templates/bootstrap/modalboxes/tpl_search_help.php

Ref # 281, 282 in prior repo
8c3f1fe
2ff26f175bfc54bdff1a7b18bfa465fcba7b958b

Use TEXT_MODAL_CLOSE for all modal displays

---

includes/templates/bootstrap/templates/tpl_ajax_checkout_confirmation_default.php

Syncs the change made a couple days ago.

Sync with regular checkout_confirmation

---

includes/templates/bootstrap/css/stylesheet.css

Update mobile menu scroll based on viewport-height

---

includes/templates/bootstrap/common/html_header.php
includes/templates/bootstrap/common/tpl_main_page.php

Refinements to mobile display

---

includes/modules/bootstrap/attributes.php
includes/modules/bootstrap/category_row.php
includes/modules/sideboxes/bootstrap/information.php
includes/modules/sideboxes/bootstrap/search.php
includes/templates/bootstrap/common/tpl_columnar_display.php
includes/templates/bootstrap/common/tpl_tabular_display.php
includes/templates/bootstrap/templates/tpl_specials_default.php

These just remove some complexity from these template files. And some of it is also being done in ZC core template files as well.

Sync some template files with base ZC code

---

includes/templates/bootstrap/css/stylesheet_zca_colors.php

And fix the footer-link color default

Add hover effect to categories and subcategories

---

YOUR_ADMIN/includes/init_includes/init_bc_config.php

Ref discussion with @dennisns7d at https://github.com/lat9/ZCA-Bootstrap-Template/pull/19#issuecomment-751839000

Improve descriptions of category-tabs hover colors

---

includes/modules/bootstrap/product_listing.php

Placeholders added for wrapper-divs and other template-specific markup, to make it easier to customize or to identify what's been customized.
Repetitive/long function calls are assigned to temporary variables which are then used in the area where markup is generated.

Incorporate updated product_listing module for easier customization

---

includes/modules/bootstrap/product_listing.php

Some of these items are only returned if the admin configuration has them enabled.

Accommodate potential undefined query result fields

---

YOUR_ADMIN/zca_bootstrap_colors.php

The removed db queries are redundant: their results are never used.
And the other code checks are redundant.

Remove unused code

---

docs/bootstrap/readme.html
includes/modules/sideboxes/bootstrap/information.php
includes/templates/bootstrap/common/tpl_offcanvas_menu.php

Sharing information sidebox

---

includes/templates/bootstrap/templates/tpl_specials_default.php

Remove unnecessary foreach in tpl_specials_default.php

---

includes/classes/zca/zca_split_page_results.php
includes/templates/bootstrap/templates/tpl_specials_default.php

This way the previous button is the same as the next button

Move ARIA_PAGINATION_PREVIOUS_PAGE to $link

---

includes/modules/bootstrap/centerboxes/featured_products.php
includes/modules/bootstrap/centerboxes/specials_index.php

Remove unneeded (and duplicate) id= attributes on centerboxes

---

includes/modules/pages/shopping_cart/header_php_shopping_cart_zca_bootstrap.php
includes/templates/bootstrap/templates/tpl_shopping_cart_default.php

For the update quantity and delete item buttons I would include both the aria-label and the title attributes
https://fontawesome.com/v5.15/how-to-use/on-the-web/other-topics/accessibility#web-fonts-semantic

Add aria-label and title in shopping cart buttons

---

includes/templates/bootstrap/common/html_header.php
includes/templates/bootstrap/css/dist-site_specific_styles.php

Add client provided stylesheet functionality

---

includes/templates/bootstrap/templates/tpl_checkout_payment_default.php
includes/templates/bootstrap/templates/tpl_login_default.php
includes/templates/bootstrap/templates/tpl_shopping_cart_default.php

These issues were found with ANDI.  
https://www.ssa.gov/accessibility/andi/help/install.html

Accessibility tweaks

---

includes/modules/bootstrap/centerboxes/manufacturer_info.php

whitespace, remove closing tag

centerboxes: manufacturer_info

---

includes/modules/bootstrap/centerboxes/specials_index.php

centerboxes: specials_index

---

includes/modules/bootstrap/bootstrap_slide_additional_images.php

as mentioned: https://github.com/lat9/ZCA-Bootstrap-Template/pull/176#issuecomment-1356016501

additional images: fix increment

---

includes/templates/bootstrap/templates/tpl_checkout_payment_default.php

without this, customer can proceed without selecting checkbox

include required code for checkbox from ZC158 default

---

includes/templates/bootstrap/common/tpl_zca_banner_carousel.php
includes/templates/bootstrap/css/stylesheet_bootstrap.carousel.css
includes/templates/bootstrap/css/stylesheet_colors.css

Corrections for #201 to enable indicators and prev/next icons to display

Banner carousels

---

includes/modules/bootstrap/centerboxes/also_purchased_products.php
includes/modules/bootstrap/centerboxes/featured_products.php
includes/modules/bootstrap/centerboxes/new_products.php
includes/modules/bootstrap/centerboxes/specials_index.php
includes/templates/bootstrap/common/tpl_main_page.php
includes/templates/bootstrap/templates/tpl_index_categories.php
includes/templates/bootstrap/templates/tpl_index_default.php

Since bootstrap  contains some core overrides, this covers the added landmark and correct heading structure for bootstrap.
No need to wait for 158 changes to merge.

Accessibility Landmark and Heading Structure

---

includes/templates/bootstrap/centerboxes/tpl_modules_no_notifications.php
includes/templates/bootstrap/centerboxes/tpl_modules_yes_notifications.php
includes/templates/bootstrap/modalboxes/tpl_ajax_search.php
includes/templates/bootstrap/sideboxes/tpl_ajax_search_header.php
includes/templates/bootstrap/sideboxes/tpl_order_history.php
includes/templates/bootstrap/templates/tpl_account_notifications_default.php
includes/templates/bootstrap/templates/tpl_checkout_payment_address_default.php
includes/templates/bootstrap/templates/tpl_checkout_shipping_address_default.php
includes/templates/bootstrap/templates/tpl_checkout_shipping_default.php
includes/templates/bootstrap/templates/tpl_login_default.php
includes/templates/bootstrap/templates/tpl_login_guest.php
includes/templates/bootstrap/templates/tpl_modules_attributes.php

Found these in testing last night

Minor h tag fixes and some aria labels 

---

includes/templates/bootstrap/modalboxes/tpl_bootstrap_images.php
includes/templates/bootstrap/templates/tpl_page_default.php
includes/templates/bootstrap/templates/tpl_products_next_previous.php

Add titles to previous and next font awesome chevrons/angles for accessibility
Added new text for next/previous image
updated verion no.

Accesability on previous and next buttons

---

includes/templates/bootstrap/templates/tpl_checkout_one_confirmation_default.php

Rearrange logic parentheses

---

includes/templates/bootstrap/templates/tpl_index_product_list.php

Add disp_order sort fix

---

includes/templates/bootstrap/templates/tpl_ajax_checkout_confirmation_default.php

Correct AJAX confirmation order-totals' layout

---

includes/modules/bootstrap/product_listing.php

fix missing end bracket

---

docs/bootstrap/readme.html
includes/modules/bootstrap/product_listing.php

Need to change itemTitle from `<h5>` to `<p>` to score 100 on accessability in google chrome

Accessabiliy issue order of headings

---

docs/bootstrap/readme.html
includes/extra_datafiles/dist.site-specific-bootstrap-settings.php
includes/templates/bootstrap/common/html_header.php

Have updated html header to font Awesome 6
Corrected error that stopped preload working
change loads to loop rather than hard coded list
Have left in the fa4-shim as bootstrap was on fa-5 it is probably not required. will take out if you don't want it.

#358: Update html_header.php

---

docs/bootstrap/readme.html
includes/templates/bootstrap/common/tpl_offcanvas_menu.php
includes/templates/bootstrap/templates/tpl_site_map_default.php

Remove usage of `ezpages::page_is_ssl`; zc210 interoperability

---

includes/templates/bootstrap/templates/tpl_order_status_default.php

Note: Holding for merge until https://github.com/zencart/zencart/pull/6676 is merged into the core.

#421: Using zc210 restructuring for `order_status` page's template

---

includes/templates/bootstrap/common/tpl_zca_banner_carousel.php

Ref v2.1.0 PR https://github.com/zencart/zencart/pull/6727

Incorporate retirement of `banners_on_ssl`

---

includes/templates/bootstrap/common/tpl_zca_banner_carousel.php

Reverts lat9/ZCA-Bootstrap-Template#437

Revert "Incorporate retirement of `banners_on_ssl`"

---

includes/templates/bootstrap/common/html_header.php
includes/templates/bootstrap/common/tpl_main_page.php

Ref: https://github.com/zencart/zencart/commit/5c9831c8d85722168c034a4f3c0d698f036a5e6f

Add new notifiers from ZC v2.1.0

---

docs/bootstrap/readme.html
includes/templates/bootstrap/templates/tpl_account_history_info_default.php

#448, in support of the to-be-updated Ty Package Tracker.

Add notifications to `account_history_info` template's status history table

---

includes/templates/bootstrap/common/tpl_header.php

Gives an icon to the other nav links in the Header Row:
- Sign Off icon for Sign Off/Log Off
- "Profile Icon" for My Account area
- Shopping Cart for Shopping Cart
- Credit Card for Checkout

Adds icons to header nav row

---

docs/bootstrap/readme.html
includes/templates/bootstrap/templates/tpl_password_reset_default.php

Add template for zc220's `password_reset` page
